M48
; DRILL file {KiCad 7.0.7} date Thu Sep 14 14:46:04 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-14T14:46:04+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X4.3619Y-2.0668
X4.3619Y-5.6101
X6.1335Y-2.0668
X6.1335Y-5.6101
T2
X4.626Y-2.0669
X5.8701Y-2.0669
T0
M30
